export const UPDATE_SONG_INFO = 'UPDATE_SONG_INFO';

export const UPDATE_GENIUS_INFO = 'UPDATE_GENIUS_INFO';

export const CHANGE_SPOTIFY_STATUS = 'CHANGE_SPOTIFY_STATUS';

export const TOGGLE_YOUTUBE = 'TOGGLE_YOUTUBE';
export const CHANGE_LYRICS_ALIGNMENT = 'CHANGE_LYRICS_ALIGNMENT';
export const CHANGE_LYRICS_FONT = 'CHANGE_LYRICS_FONT';
export const TOGGLE_LYRICS_ITALICIZED = 'TOGGLE_LYRICS_ITALICIZED';
export const CHANGE_APP_BRIGHTNESS = 'CHANGE_APP_BRIGHTNESS';
